name: TimeQuest
options:
  bundleIdPrefix: com.timequest
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.2"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"

targets:
  TimeQuest:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Models
      - path: Repositories
      - path: Domain
      - path: Features
      - path: Game
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.timequest.app
        INFOPLIST_KEY_CFBundleDisplayName: TimeQuest
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: SwiftData.framework
      - sdk: SpriteKit.framework
      - sdk: CryptoKit.framework
